# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/Debug
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Tablaturnd
  DEFINES   += -DDEBUG
  INCLUDES  += -Isrc -Icommon -Ilib/fmod/inc -Ilib/opencv2/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -g
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -Llib/fmod -Llib/opencv2 -Llib/fmod/lib -Llib/fmod/inc -Llib/opencv2/lib -Llib/opencv2/include -Llib/opencv2/include/opencv2 -Llib/opencv2/include/opencv2/ocl -Llib/opencv2/include/opencv2/objdetect -Llib/opencv2/include/opencv2/gpu -Llib/opencv2/include/opencv2/stitching -Llib/opencv2/include/opencv2/nonfree -Llib/opencv2/include/opencv2/videostab -Llib/opencv2/include/opencv2/imgproc -Llib/opencv2/include/opencv2/video -Llib/opencv2/include/opencv2/superres -Llib/opencv2/include/opencv2/calib3d -Llib/opencv2/include/opencv2/ml -Llib/opencv2/include/opencv2/contrib -Llib/opencv2/include/opencv2/features2d -Llib/opencv2/include/opencv2/highgui -Llib/opencv2/include/opencv2/core -Llib/opencv2/include/opencv2/flann -Llib/opencv2/include/opencv2/ts -Llib/opencv2/include/opencv2/photo -Llib/opencv2/include/opencv2/legacy -Llib/opencv2/include/opencv2/gpu/device -Llib/opencv2/include/opencv2/gpu/device/detail -Llib/opencv2/include/opencv2/stitching/detail
  LIBS      += -lX11 -lXrandr -lrt -lpthread -lfmodex64 -lSDL -lSDL_image -lSDL_ttf -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/Release
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Tablaturnr
  DEFINES   += -DNDEBUG
  INCLUDES  += -Isrc -Icommon -Ilib/fmod/inc -Ilib/opencv2/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -Llib/fmod -Llib/opencv2 -Llib/fmod/lib -Llib/fmod/inc -Llib/opencv2/lib -Llib/opencv2/include -Llib/opencv2/include/opencv2 -Llib/opencv2/include/opencv2/ocl -Llib/opencv2/include/opencv2/objdetect -Llib/opencv2/include/opencv2/gpu -Llib/opencv2/include/opencv2/stitching -Llib/opencv2/include/opencv2/nonfree -Llib/opencv2/include/opencv2/videostab -Llib/opencv2/include/opencv2/imgproc -Llib/opencv2/include/opencv2/video -Llib/opencv2/include/opencv2/superres -Llib/opencv2/include/opencv2/calib3d -Llib/opencv2/include/opencv2/ml -Llib/opencv2/include/opencv2/contrib -Llib/opencv2/include/opencv2/features2d -Llib/opencv2/include/opencv2/highgui -Llib/opencv2/include/opencv2/core -Llib/opencv2/include/opencv2/flann -Llib/opencv2/include/opencv2/ts -Llib/opencv2/include/opencv2/photo -Llib/opencv2/include/opencv2/legacy -Llib/opencv2/include/opencv2/gpu/device -Llib/opencv2/include/opencv2/gpu/device/detail -Llib/opencv2/include/opencv2/stitching/detail
  LIBS      += -lX11 -lXrandr -lrt -lpthread -lfmodex64 -lSDL -lSDL_image -lSDL_ttf -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Tablaturnd
  DEFINES   += -DDEBUG
  INCLUDES  += -Isrc -Icommon -Ilib/fmod/inc -Ilib/opencv2/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -g -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m64 -L/usr/lib64 -Llib/fmod -Llib/opencv2 -Llib/fmod/lib -Llib/fmod/inc -Llib/opencv2/lib -Llib/opencv2/include -Llib/opencv2/include/opencv2 -Llib/opencv2/include/opencv2/ocl -Llib/opencv2/include/opencv2/objdetect -Llib/opencv2/include/opencv2/gpu -Llib/opencv2/include/opencv2/stitching -Llib/opencv2/include/opencv2/nonfree -Llib/opencv2/include/opencv2/videostab -Llib/opencv2/include/opencv2/imgproc -Llib/opencv2/include/opencv2/video -Llib/opencv2/include/opencv2/superres -Llib/opencv2/include/opencv2/calib3d -Llib/opencv2/include/opencv2/ml -Llib/opencv2/include/opencv2/contrib -Llib/opencv2/include/opencv2/features2d -Llib/opencv2/include/opencv2/highgui -Llib/opencv2/include/opencv2/core -Llib/opencv2/include/opencv2/flann -Llib/opencv2/include/opencv2/ts -Llib/opencv2/include/opencv2/photo -Llib/opencv2/include/opencv2/legacy -Llib/opencv2/include/opencv2/gpu/device -Llib/opencv2/include/opencv2/gpu/device/detail -Llib/opencv2/include/opencv2/stitching/detail
  LIBS      += -lX11 -lXrandr -lrt -lpthread -lfmodex64 -lSDL -lSDL_image -lSDL_ttf -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Tablaturnr
  DEFINES   += -DNDEBUG
  INCLUDES  += -Isrc -Icommon -Ilib/fmod/inc -Ilib/opencv2/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m64 -L/usr/lib64 -Llib/fmod -Llib/opencv2 -Llib/fmod/lib -Llib/fmod/inc -Llib/opencv2/lib -Llib/opencv2/include -Llib/opencv2/include/opencv2 -Llib/opencv2/include/opencv2/ocl -Llib/opencv2/include/opencv2/objdetect -Llib/opencv2/include/opencv2/gpu -Llib/opencv2/include/opencv2/stitching -Llib/opencv2/include/opencv2/nonfree -Llib/opencv2/include/opencv2/videostab -Llib/opencv2/include/opencv2/imgproc -Llib/opencv2/include/opencv2/video -Llib/opencv2/include/opencv2/superres -Llib/opencv2/include/opencv2/calib3d -Llib/opencv2/include/opencv2/ml -Llib/opencv2/include/opencv2/contrib -Llib/opencv2/include/opencv2/features2d -Llib/opencv2/include/opencv2/highgui -Llib/opencv2/include/opencv2/core -Llib/opencv2/include/opencv2/flann -Llib/opencv2/include/opencv2/ts -Llib/opencv2/include/opencv2/photo -Llib/opencv2/include/opencv2/legacy -Llib/opencv2/include/opencv2/gpu/device -Llib/opencv2/include/opencv2/gpu/device/detail -Llib/opencv2/include/opencv2/stitching/detail
  LIBS      += -lX11 -lXrandr -lrt -lpthread -lfmodex64 -lSDL -lSDL_image -lSDL_ttf -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Tablaturnd
  DEFINES   += -DDEBUG
  INCLUDES  += -Isrc -Icommon -Ilib/fmod/inc -Ilib/opencv2/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m32 -L/usr/lib32 -Llib/fmod -Llib/opencv2 -Llib/fmod/lib -Llib/fmod/inc -Llib/opencv2/lib -Llib/opencv2/include -Llib/opencv2/include/opencv2 -Llib/opencv2/include/opencv2/ocl -Llib/opencv2/include/opencv2/objdetect -Llib/opencv2/include/opencv2/gpu -Llib/opencv2/include/opencv2/stitching -Llib/opencv2/include/opencv2/nonfree -Llib/opencv2/include/opencv2/videostab -Llib/opencv2/include/opencv2/imgproc -Llib/opencv2/include/opencv2/video -Llib/opencv2/include/opencv2/superres -Llib/opencv2/include/opencv2/calib3d -Llib/opencv2/include/opencv2/ml -Llib/opencv2/include/opencv2/contrib -Llib/opencv2/include/opencv2/features2d -Llib/opencv2/include/opencv2/highgui -Llib/opencv2/include/opencv2/core -Llib/opencv2/include/opencv2/flann -Llib/opencv2/include/opencv2/ts -Llib/opencv2/include/opencv2/photo -Llib/opencv2/include/opencv2/legacy -Llib/opencv2/include/opencv2/gpu/device -Llib/opencv2/include/opencv2/gpu/device/detail -Llib/opencv2/include/opencv2/stitching/detail
  LIBS      += -lX11 -lXrandr -lrt -lpthread -lfmodex64 -lSDL -lSDL_image -lSDL_ttf -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Tablaturnr
  DEFINES   += -DNDEBUG
  INCLUDES  += -Isrc -Icommon -Ilib/fmod/inc -Ilib/opencv2/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m32 -L/usr/lib32 -Llib/fmod -Llib/opencv2 -Llib/fmod/lib -Llib/fmod/inc -Llib/opencv2/lib -Llib/opencv2/include -Llib/opencv2/include/opencv2 -Llib/opencv2/include/opencv2/ocl -Llib/opencv2/include/opencv2/objdetect -Llib/opencv2/include/opencv2/gpu -Llib/opencv2/include/opencv2/stitching -Llib/opencv2/include/opencv2/nonfree -Llib/opencv2/include/opencv2/videostab -Llib/opencv2/include/opencv2/imgproc -Llib/opencv2/include/opencv2/video -Llib/opencv2/include/opencv2/superres -Llib/opencv2/include/opencv2/calib3d -Llib/opencv2/include/opencv2/ml -Llib/opencv2/include/opencv2/contrib -Llib/opencv2/include/opencv2/features2d -Llib/opencv2/include/opencv2/highgui -Llib/opencv2/include/opencv2/core -Llib/opencv2/include/opencv2/flann -Llib/opencv2/include/opencv2/ts -Llib/opencv2/include/opencv2/photo -Llib/opencv2/include/opencv2/legacy -Llib/opencv2/include/opencv2/gpu/device -Llib/opencv2/include/opencv2/gpu/device/detail -Llib/opencv2/include/opencv2/stitching/detail
  LIBS      += -lX11 -lXrandr -lrt -lpthread -lfmodex64 -lSDL -lSDL_image -lSDL_ttf -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/main.o \
	$(OBJDIR)/SoundPlayer.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking Tablaturn
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Tablaturn
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/main.o: src/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SoundPlayer.o: src/sound/SoundPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
